#!/bin/sh

set -e

case "$1" in
  install|upgrade)
    # We need to move aside the old generated directory, as the new package
    # ships compat symlinks at the same location.
    if [ -d /etc/ngcp-tests ]; then
      if [ -d /etc/ngcp-system-tests ]; then
        rm -rf /etc/ngcp-tests
      else
        mv /etc/ngcp-tests /etc/ngcp-system-tests
      fi
    fi
    ;;
  abort-upgrade)
    ;;
  *)
    echo "preinst called with unknown argument '$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#
