#!/bin/sh
# This script can be called in the following ways:
#
# After the package was removed:
# <postrm> remove
#
# After the package was purged:
# <postrm> purge
#
# After the package was upgraded:
# <old-postrm> upgrade <new-version>
# if that fails:
# <new-postrm> failed-upgrade <old-version>
#
#
# After all of the packages files have been replaced:
# <postrm> disappear <overwriting-package> <version>
#
#
# If preinst fails during install:
# <new-postrm> abort-install
#
# If preinst fails during upgrade of removed package:
# <new-postrm> abort-install <old-version>
#
# If preinst fails during upgrade:
# <new-postrm> abort-upgrade <old-version>

set -e

case "$1" in
  purge)
    rm -rf /etc/ngcp-system-tests/
    # Remove old location too.
    rm -rf /etc/ngcp-tests/
  ;;

  remove|upgrade|failed-upgrade|disappear|abort-install|abort-upgrade)
  ;;

  *)
    echo "postrm called with unknown argument '$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
